-- MySQL Script generated by MySQL Workbench
-- Fri Dec  5 12:50:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema talkmix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema talkmix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `talkmix` DEFAULT CHARACTER SET utf8 ;
USE `talkmix` ;

-- -----------------------------------------------------
-- Table `talkmix`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talkmix`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(225) NOT NULL,
  `Sobrenome` VARCHAR(225) NOT NULL,
  `Senha` VARCHAR(225) NOT NULL,
  `Email` VARCHAR(225) NOT NULL,
  `N_livros_lidos` INT NULL,
  `Ultimo_login` DATE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `talkmix`.`Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talkmix`.`Livros` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(15) NOT NULL,
  `Titulo` VARCHAR(255) NOT NULL,
  `Autor` VARCHAR(255) NOT NULL,
  `Editora` VARCHAR(255) NULL,
  `Data_publicacao` DATETIME NULL,
  `Sinopse` VARCHAR(255) NULL,
  `Numero_pagina` INT NULL,
  `Genero` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `talkmix`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talkmix`.`Comentarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Comentario` VARCHAR(280) NOT NULL,
  `Data_comentario` DATETIME NOT NULL,
  `Usuario_ID` INT NOT NULL,
  `Livros_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Usuario_ID`, `Livros_ID`),
  INDEX `fk_Comentarios_Usuario_idx` (`Usuario_ID` ASC) VISIBLE,
  INDEX `fk_Comentarios_Livros1_idx` (`Livros_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `talkmix`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Livros1`
    FOREIGN KEY (`Livros_ID`)
    REFERENCES `talkmix`.`Livros` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `talkmix`.`Leituras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talkmix`.`Leituras` (
  `idLeituras` INT NOT NULL AUTO_INCREMENT,
  `Data_leitura` DATETIME NOT NULL,
  `Usuario_ID` INT NOT NULL,
  `Livros_ID` INT NOT NULL,
  PRIMARY KEY (`idLeituras`, `Usuario_ID`, `Livros_ID`),
  INDEX `fk_Leituras_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  INDEX `fk_Leituras_Livros1_idx` (`Livros_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Leituras_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `talkmix`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leituras_Livros1`
    FOREIGN KEY (`Livros_ID`)
    REFERENCES `talkmix`.`Livros` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `talkmix`.`Meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talkmix`.`Meta` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `N_livros_meta` INT NOT NULL,
  `N_livros_lidos_periodo` INT NOT NULL,
  `Data_criacao_meta` DATETIME NOT NULL,
  `Data_finalização_meta` DATETIME NOT NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Usuario_ID`),
  INDEX `fk_Meta_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Meta_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `talkmix`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
